apiVersion: v1
kind: Service
metadata:
  labels:
    service: broker
  name: broker
  namespace: default
spec:
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9101"
      port: 9101
      targetPort: 9101
  selector:
    service: broker
status:
  loadBalancer: {}
