apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: spark-worker-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: spark-worker-2
    spec:
      containers:
        - env:
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_MASTER_URL
              value: spark://spark:7077
            - name: SPARK_MODE
              value: worker
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: SPARK_USER
              value: spark
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: 1G
          image: peoplesjwilson/streaming-pipeline:spark-worker
          name: spark-worker-2
          resources: {}
      restartPolicy: Always
status: {}