apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
              ephemeral-storage: "4096Mi"
      restartPolicy: Always
status: {}
